version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "zed_extension_api"
        versions: [">=0.7.0"]
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/editors/code"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/vscode"
  - package-ecosystem: "npm"
    directory: "/npm/panache-cli"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
