id = "panache"
name = "Panache"
description = "Language server for Pandoc, Quarto, and R Markdown"
version = "2.31.0"
schema_version = 1
authors = ["Johan Larsson <johan@jolars.co>"]
repository = "https://github.com/jolars/panache"

[language_servers.panache]
name = "Panache Language Server"
languages = ["Markdown", "Quarto", "RMarkdown"]
