[formatters]
r = "air"
yaml = "yamlfmt"
toml = "taplo"
bash = "shfmt"
sh = "shfmt"
python = "ruff"

[formatters.taplo]
cmd = "taplo"
args = ["format", "-"]

[formatters.shfmt]
cmd = "shfmt"
args = ["-"]

[formatters.ruff]
cmd = "ruff"
args = ["format", "--stdin-filename", "{}", "-"]

[linters]
r = "jarl"
