//! Consumer-conditioned YAML validation tests.
//!
//! These hold Panache's per-(flavor, location) YAML acceptance against the
//! empirical oracle audit (`scripts/yaml-oracle/oracle.json`, regenerated by
//! `scripts/yaml-oracle/run.sh`) and against the classification in
//! `tests/yaml/consumer-matrix.md`.
//!
//! The 1.2 substrate is tested separately by `tests/yaml.rs`; here we only
//! exercise the consumer-only layer (implicit empty keys, duplicate keys).

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use panache_parser::Flavor;
use panache_parser::parser::yaml::{YamlValidationContext, locate_yaml_diagnostic_ctx};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn fixture_root() -> PathBuf {
    manifest_dir().join("tests/fixtures/yaml-test-suite")
}

fn oracle_path() -> PathBuf {
    manifest_dir().join("../../scripts/yaml-oracle/oracle.json")
}

/// One oracle record (subset of the fields we assert on).
struct OracleCase {
    id: String,
    yaml12: String,
    multidoc: bool,
    pandoc_direct: String,
    jsyaml: String,
    ryaml: String,
}

fn load_oracle() -> (serde_json::Value, Vec<OracleCase>) {
    let raw = fs::read_to_string(oracle_path()).unwrap_or_else(|e| {
        panic!(
            "failed to read {} — regenerate with scripts/yaml-oracle/run.sh: {e}",
            oracle_path().display()
        )
    });
    let json: serde_json::Value = serde_json::from_str(&raw).expect("oracle.json is valid JSON");
    let cases = json["cases"]
        .as_array()
        .expect("oracle.json has a cases array")
        .iter()
        .map(|c| OracleCase {
            id: c["id"].as_str().unwrap().to_string(),
            yaml12: c["yaml12"].as_str().unwrap().to_string(),
            multidoc: c["multidoc"].as_bool().unwrap(),
            pandoc_direct: c["pandoc_direct"].as_str().unwrap().to_string(),
            jsyaml: c["jsyaml"].as_str().unwrap().to_string(),
            ryaml: c["ryaml"].as_str().unwrap().to_string(),
        })
        .collect();
    (json, cases)
}

fn case_input(id: &str) -> String {
    let path = fixture_root().join(id).join("in.yaml");
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn rejects(input: &str, ctx: YamlValidationContext) -> bool {
    locate_yaml_diagnostic_ctx(input, "", ctx).is_some()
}

fn is_err(verdict: &str) -> bool {
    verdict.starts_with("err:")
}

/// Soundness: a consumer-only rejection (one the 1.2 substrate would NOT make)
/// may only fire when a real consumer of that (flavor, location) actually
/// rejects the document, per the oracle. This is the no-false-positive guard
/// over the WHOLE suite — our Pool-2 checks must never flag YAML that the
/// pipeline accepts.
#[test]
fn consumer_rejections_are_sound_against_oracle() {
    let (_json, cases) = load_oracle();
    let substrate = YamlValidationContext::substrate();
    let pandoc_fm = YamlValidationContext::frontmatter(Flavor::Pandoc);
    let quarto_fm = YamlValidationContext::frontmatter(Flavor::Quarto);
    let rmd_fm = YamlValidationContext::frontmatter(Flavor::RMarkdown);
    let rmd_hp = YamlValidationContext::hashpipe(Flavor::RMarkdown);

    let mut checked = 0usize;
    for case in &cases {
        // Frontmatter is single-document; multi-doc cases can't occur there.
        if case.multidoc {
            continue;
        }
        let input = case_input(&case.id);

        // Isolate the Pool-2 effect: only consider cases the substrate accepts.
        if rejects(&input, substrate) {
            continue;
        }
        checked += 1;

        // Pandoc frontmatter = {libyaml}; ground truth = pandoc_direct.
        if rejects(&input, pandoc_fm) {
            assert!(
                is_err(&case.pandoc_direct),
                "case {}: Panache rejects under (Pandoc, frontmatter) but pandoc accepts it \
                 (pandoc_direct={:?}). Consumer check produced a false positive.",
                case.id,
                case.pandoc_direct
            );
        }

        // Quarto frontmatter = {libyaml, jsyaml}; rejects iff either does.
        if rejects(&input, quarto_fm) {
            assert!(
                is_err(&case.pandoc_direct) || is_err(&case.jsyaml),
                "case {}: Panache rejects under (Quarto, frontmatter) but BOTH pandoc and \
                 js-yaml accept it (pandoc_direct={:?}, jsyaml={:?}). False positive.",
                case.id,
                case.pandoc_direct,
                case.jsyaml
            );
        }

        // RMarkdown frontmatter = {libyaml, R-yaml}; rejects iff either does.
        if rejects(&input, rmd_fm) {
            assert!(
                is_err(&case.pandoc_direct) || is_err(&case.ryaml),
                "case {}: Panache rejects under (RMarkdown, frontmatter) but BOTH pandoc and \
                 R-yaml accept it (pandoc_direct={:?}, ryaml={:?}). False positive.",
                case.id,
                case.pandoc_direct,
                case.ryaml
            );
        }

        // RMarkdown hashpipe = {R-yaml}; ground truth = ryaml.
        if rejects(&input, rmd_hp) {
            assert!(
                is_err(&case.ryaml),
                "case {}: Panache rejects under (RMarkdown, hashpipe) but R-yaml accepts it \
                 (ryaml={:?}). False positive.",
                case.id,
                case.ryaml
            );
        }
    }
    assert!(
        checked > 100,
        "expected to exercise many substrate-valid cases, only saw {checked}"
    );
}

/// Coverage: the implicit-empty-key family is rejected under every real flavor,
/// and stays accepted under the lenient flavors and the substrate.
#[test]
fn implicit_empty_key_rejected_by_real_consumers() {
    // `: a` — a block mapping entry whose key is empty.
    let body = ": a\n";
    let fm = |flavor| rejects(body, YamlValidationContext::frontmatter(flavor));

    assert!(fm(Flavor::Pandoc), "pandoc frontmatter rejects empty key");
    assert!(fm(Flavor::Quarto), "quarto frontmatter rejects empty key");
    assert!(
        fm(Flavor::RMarkdown),
        "rmarkdown frontmatter rejects empty key"
    );
    assert!(
        rejects(body, YamlValidationContext::hashpipe(Flavor::Quarto)),
        "quarto hashpipe rejects empty key"
    );

    // Lenient + substrate accept it (valid YAML 1.2).
    assert!(!fm(Flavor::CommonMark), "commonmark frontmatter is lenient");
    assert!(
        !rejects(body, YamlValidationContext::substrate()),
        "substrate keeps the 1.2 verdict (valid)"
    );
}

/// A flow-context empty key (`[:x]`) and a normal key are accepted everywhere —
/// the empty-key check is block-only and must not over-reach.
#[test]
fn flow_empty_key_and_normal_key_accepted() {
    for body in ["foo: [:x]\n", "a: 1\nb: 2\n"] {
        for flavor in [Flavor::Pandoc, Flavor::Quarto, Flavor::RMarkdown] {
            assert!(
                !rejects(body, YamlValidationContext::frontmatter(flavor)),
                "{flavor:?} frontmatter should accept {body:?}"
            );
        }
    }
}

/// Coverage: duplicate keys are rejected by js-yaml (Quarto) and R-yaml
/// (RMarkdown), but accepted by pandoc/libyaml (last value wins). Verified
/// empirically: js-yaml `duplicated mapping key`, R `yaml` `Duplicate map key`,
/// pandoc/Ruby-Psych accept.
#[test]
fn duplicate_key_rejected_by_jsyaml_and_ryaml() {
    let body = "a: 1\na: 2\n";

    // js-yaml (Quarto) and R-yaml (RMarkdown) consumers reject.
    assert!(rejects(
        body,
        YamlValidationContext::frontmatter(Flavor::Quarto)
    ));
    assert!(rejects(
        body,
        YamlValidationContext::hashpipe(Flavor::Quarto)
    ));
    assert!(
        rejects(body, YamlValidationContext::frontmatter(Flavor::RMarkdown)),
        "rmarkdown frontmatter (R yaml) rejects duplicate keys"
    );
    assert!(
        rejects(body, YamlValidationContext::hashpipe(Flavor::RMarkdown)),
        "rmarkdown hashpipe (knitr/R yaml) rejects duplicate keys"
    );

    // Pandoc/libyaml accepts (last value wins).
    assert!(!rejects(
        body,
        YamlValidationContext::frontmatter(Flavor::Pandoc)
    ));

    // Substrate keeps the 1.2 verdict (duplicate keys are valid YAML 1.2).
    assert!(!rejects(body, YamlValidationContext::substrate()));
}

/// The fixture tree's (id, yaml12) verdicts must match what `oracle.json` was
/// generated from. A yaml-test-suite refresh that adds, removes, or flips a
/// case changes this and must be a reviewed event: regenerate the oracle and
/// re-audit `consumer-matrix.md`.
#[test]
fn oracle_matches_live_fixture_verdicts() {
    let (_json, cases) = load_oracle();
    let oracle_verdicts: BTreeMap<&str, &str> = cases
        .iter()
        .map(|c| (c.id.as_str(), c.yaml12.as_str()))
        .collect();

    let mut live: BTreeMap<String, String> = BTreeMap::new();
    collect_fixture_verdicts(&fixture_root(), &mut live);

    let regen = "fixtures changed; regenerate scripts/yaml-oracle/oracle.json via \
                 scripts/yaml-oracle/run.sh and re-review tests/yaml/consumer-matrix.md";

    assert_eq!(
        oracle_verdicts.len(),
        live.len(),
        "oracle case count ({}) != live fixture count ({}). {regen}",
        oracle_verdicts.len(),
        live.len()
    );
    for (id, verdict) in &live {
        match oracle_verdicts.get(id.as_str()) {
            Some(&recorded) => assert_eq!(
                recorded, verdict,
                "case {id}: oracle yaml12={recorded:?} but fixture says {verdict:?}. {regen}"
            ),
            None => panic!("case {id} present in fixtures but missing from oracle.json. {regen}"),
        }
    }
}

/// Walk the fixture tree exactly like the suite harness (`tests/yaml.rs`):
/// top-level `in.yaml` cases plus numbered subcases under 4-char hashed
/// parents; `name/` and `tags/` symlink indexes are skipped.
fn collect_fixture_verdicts(root: &Path, out: &mut BTreeMap<String, String>) {
    for entry in fs::read_dir(root).expect("read fixture root") {
        let path = entry.expect("dir entry").path();
        if !path.is_dir() {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap()
            .to_string();
        if path.join("in.yaml").exists() {
            out.insert(name, verdict_for(&path));
            continue;
        }
        let is_hashed_parent = name.len() == 4
            && name
                .chars()
                .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit());
        if !is_hashed_parent {
            continue;
        }
        for sub in fs::read_dir(&path).expect("read hashed parent") {
            let sub_path = sub.expect("dir entry").path();
            if !sub_path.is_dir() || !sub_path.join("in.yaml").exists() {
                continue;
            }
            let sub_name = sub_path.file_name().and_then(|s| s.to_str()).unwrap();
            out.insert(format!("{name}/{sub_name}"), verdict_for(&sub_path));
        }
    }
}

fn verdict_for(case_dir: &Path) -> String {
    if case_dir.join("error").exists() {
        "error".to_string()
    } else {
        "valid".to_string()
    }
}
