---
title: "User Guide"
---

This section of the documentation provides user-facing guides and instructions
for using Panache, including installation.

- In [Formatting](formatting.qmd) you can find instructions on how to use
  Panache to format your documents, showing examples of the formatting rules and
  how to customize them.

- In [Linting](linting.qmd) you can find instructions on how to use Panache to
  lint your documents, showing examples of the linting rules and how to
  customize them.

- In [Language Server](lsp.qmd) we describe the Panache Language Server, which
  beyond formatting and linting also provides features like code completion,
  hover information, document/workspace symbols, renaming, and code actions.

- In [configuration](configuration.qmd) we describe how to configure Panache,
  both globally and on a per-project basis, and how to use configuration files
  to customize the formatting and linting rules.

- In [Integrations](integrations.qmd) we describe how to integrate Panache with
  other tools, such as pre-commit hooks and GitHub actions, to automatically
  format and lint your documents on commit or pull request.
