#!/usr/bin/env python3
"""Generate Panache's unicode-math atom-classification data.

Usage::

    scripts/gen_math_symbols.py                 # check sync, exit 1 on drift
    scripts/gen_math_symbols.py --write         # regenerate data and license
    scripts/gen_math_symbols.py --source PATH   # use a local checkout or table
    scripts/gen_math_symbols.py --selftest      # run offline unit checks
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "crates" / "panache-parser" / "data"
DATA_FILE = DATA_DIR / "math_symbols.json"
LICENSE_FILE = DATA_DIR / "unicode-math.LICENSE"
NOTICE_FILE = DATA_DIR / "unicode-math.NOTICE"

UNICODE_MATH_REPO = "https://github.com/latex3/unicode-math"
UNICODE_MATH_REF = "936812ed7407cd2b2f06bf4c97f12275a6b2e781"
TABLE_URL = (
    "https://raw.githubusercontent.com/latex3/unicode-math/"
    f"{UNICODE_MATH_REF}/unicode-math-table.tex"
)
LICENSE_URL = (
    "https://raw.githubusercontent.com/latex3/unicode-math/"
    f"{UNICODE_MATH_REF}/LICENSE"
)
EXPECTED_ROWS = 2448

LINE_RE = re.compile(
    r'^\\UnicodeMathSymbol\{"([0-9A-F]+)\}\{\\([^ }]+)\s*\}'
    r'\{\\(math[^}]+)\}\{.*\}%$'
)

DIRECT_CLASSES = {
    "mathop": "op",
    "mathbin": "bin",
    "mathrel": "rel",
    "mathopen": "open",
    "mathclose": "close",
    "mathpunct": "punct",
    "mathfence": "fence",
}


def normalize_class(raw: str) -> str:
    """Project unicode-math symbol kinds onto Panache's atom family."""
    return DIRECT_CLASSES.get(raw, "ord")


def delimiter_role(raw: str) -> str | None:
    """Return the delimiter role before Panache's curated exceptions."""
    return {
        "mathopen": "open",
        "mathclose": "close",
        "mathfence": "fence",
    }.get(raw)


def parse_table(text: str) -> list[list[str | None]]:
    rows: list[list[str | None]] = []
    commands: set[str] = set()
    matched_lines = 0
    for line_no, line in enumerate(text.splitlines(), 1):
        if not line.startswith("\\UnicodeMathSymbol"):
            continue
        matched_lines += 1
        match = LINE_RE.fullmatch(line)
        if match is None:
            raise ValueError(f"malformed symbol row at line {line_no}: {line}")
        codepoint, command, raw_class = match.groups()
        value = int(codepoint, 16)
        if value > 0x10FFFF or 0xD800 <= value <= 0xDFFF:
            raise ValueError(f"invalid Unicode scalar U+{codepoint} at line {line_no}")
        if command in commands:
            raise ValueError(f"duplicate command `{command}` at line {line_no}")
        commands.add(command)
        rows.append(
            [
                f"{value:05X}",
                command,
                normalize_class(raw_class),
                delimiter_role(raw_class),
            ]
        )
    if matched_lines != len(rows):
        raise AssertionError("every symbol line must produce exactly one row")
    return rows


def render(rows: list[list[str | None]]) -> str:
    payload = {
        "_comment": (
            "GENERATED by scripts/gen_math_symbols.py -- do not edit by hand. "
            "Mechanical Unicode code-point, primary command-name, and TeX-class "
            f"facts from unicode-math's unicode-math-table.tex at {UNICODE_MATH_REF}. "
            "The upstream work is distributed under LPPL 1.3c or later; see "
            "unicode-math.LICENSE. Curated Panache overrides live in "
            "src/semantic/math.rs. Run `task math-symbols:sync` to regenerate."
        ),
        "source": {
            "repository": UNICODE_MATH_REPO,
            "revision": UNICODE_MATH_REF,
            "path": "unicode-math-table.tex",
            "license": "LPPL-1.3c-or-later",
        },
        "symbols": rows,
    }
    return json.dumps(payload, ensure_ascii=False, indent=1) + "\n"


def render_notice() -> str:
    return f"""unicode-math symbol data

crates/panache-parser/data/math_symbols.json is a normalized extract of
unicode-math-table.tex from unicode-math v0.8r at revision
{UNICODE_MATH_REF}:

  {UNICODE_MATH_REPO}

The extract retains Unicode code points, primary command names, and math classes.
Panache maps classes onto its smaller semantic class family and supplies separate
curated overrides in crates/panache-parser/src/semantic/math.rs.

The upstream work is distributed under the LaTeX Project Public License, version
1.3c or later. The full license is packaged as unicode-math.LICENSE.

Copyright 2006-2019 Will Robertson, LPPL maintainer
Copyright 2010-2017 Philipp Stephani
Copyright 2011-2017 Joseph Wright
Copyright 2012-2015 Khaled Hosny
"""


def read_sources(source: str | None) -> tuple[str, str]:
    if source is None:
        with urllib.request.urlopen(TABLE_URL) as response:
            table = response.read().decode("utf-8")
        with urllib.request.urlopen(LICENSE_URL) as response:
            license_text = response.read().decode("utf-8")
        return table, license_text

    path = Path(source)
    if path.is_dir():
        return (
            (path / "unicode-math-table.tex").read_text(),
            (path / "LICENSE").read_text(),
        )
    return path.read_text(), path.with_name("LICENSE").read_text()


def write_or_check(path: Path, rendered: str, write: bool) -> int:
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered)
        print(f"wrote {path.relative_to(ROOT)}")
        return 0
    current = path.read_text() if path.is_file() else ""
    if current == rendered:
        print(f"{path.name} is in sync")
        return 0
    print(f"{path.name} is OUT OF SYNC.", file=sys.stderr)
    print("run `task math-symbols:sync` to regenerate.", file=sys.stderr)
    return 1


def selftest() -> int:
    sample = """\
\\UnicodeMathSymbol{"0002B}{\\mathplus }{\\mathbin}{plus}%
\\UnicodeMathSymbol{"0221A}{\\sqrt }{\\mathopen}{radical}%
\\UnicodeMathSymbol{"0221A}{\\surd }{\\mathord}{radical alias}%
\\UnicodeMathSymbol{"1F600}{\\face }{\\mathalpha}{face}%
"""
    rows = parse_table(sample)
    assert rows == [
        ["0002B", "mathplus", "bin", None],
        ["0221A", "sqrt", "open", "open"],
        ["0221A", "surd", "ord", None],
        ["1F600", "face", "ord", None],
    ]
    try:
        parse_table('\\UnicodeMathSymbol{"0}{\\x}{\\mathord}\n')
    except ValueError:
        pass
    else:
        raise AssertionError("malformed rows must be rejected")
    print("selftest: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--write", action="store_true", help="regenerate tracked files")
    parser.add_argument("--source", metavar="PATH", help="local checkout or table path")
    parser.add_argument("--selftest", action="store_true", help="run offline unit checks")
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    table, license_text = read_sources(args.source)
    rows = parse_table(table)
    if len(rows) != EXPECTED_ROWS:
        raise SystemExit(
            f"expected {EXPECTED_ROWS} rows at the pinned revision, found {len(rows)}"
        )
    rc = write_or_check(DATA_FILE, render(rows), args.write)
    rc |= write_or_check(LICENSE_FILE, license_text, args.write)
    rc |= write_or_check(NOTICE_FILE, render_notice(), args.write)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
