//! Generates static lookup tables used by the parser.
//!
//! The bare-URI table comes from the vendored IANA registry. The math-symbol
//! tables come from Panache's pinned, normalized unicode-math extract. Both are
//! compiled into read-only Rust data so parsing never reads or decodes them at
//! runtime.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

const UNICODE_MATH_REPOSITORY: &str = "https://github.com/latex3/unicode-math";
const UNICODE_MATH_REVISION: &str = "936812ed7407cd2b2f06bf4c97f12275a6b2e781";
const EXPECTED_MATH_SYMBOLS: usize = 2_448;

#[derive(Deserialize, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum RawMathClass {
    Ord,
    Op,
    Bin,
    Rel,
    Open,
    Close,
    Punct,
    Fence,
}

impl RawMathClass {
    fn variant(self) -> &'static str {
        match self {
            Self::Ord => "MathClass::Ord",
            Self::Op => "MathClass::Op",
            Self::Bin => "MathClass::Bin",
            Self::Rel => "MathClass::Rel",
            Self::Open => "MathClass::Open",
            Self::Close => "MathClass::Close",
            Self::Punct => "MathClass::Punct",
            Self::Fence => "MathClass::Fence",
        }
    }
}

#[derive(Deserialize, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum RawDelimiterRole {
    Open,
    Close,
    Fence,
}

impl RawDelimiterRole {
    fn variant(self) -> &'static str {
        match self {
            Self::Open => "DelimiterRole::Open",
            Self::Close => "DelimiterRole::Close",
            Self::Fence => "DelimiterRole::Fence",
        }
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawMathSymbols {
    #[serde(rename = "_comment")]
    _comment: serde::de::IgnoredAny,
    source: RawMathSource,
    symbols: Vec<(String, String, RawMathClass, Option<RawDelimiterRole>)>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawMathSource {
    repository: String,
    revision: String,
    path: String,
    license: String,
}

/// Nonstandard schemes that pandoc autolinks but the IANA registry omits.
/// Taken from pandoc's `Text.Pandoc.URI.schemes`;
/// folded in alongside the registry and deduped after sorting.
const NONSTANDARD_SCHEMES: &[&str] = &["doi", "gemini", "isbn", "javascript", "pmid"];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let csv_path = manifest_dir.join("src/parser/inlines/uri-schemes.csv");
    let csv = fs::read_to_string(&csv_path).expect("read uri-schemes.csv");

    let mut schemes = parse_iana_schemes(&csv);
    schemes.extend(NONSTANDARD_SCHEMES.iter().map(|s| s.to_string()));
    schemes.sort();
    schemes.dedup();

    let mut out = String::from("// @generated by build.rs from uri-schemes.csv — do not edit.\n");
    out.push_str("const BARE_URI_SCHEMES: &[&str] = &[\n");
    for scheme in &schemes {
        out.push_str("    \"");
        out.push_str(scheme);
        out.push_str("\",\n");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("uri_schemes.rs"), out).expect("write generated scheme table");

    generate_math_symbols(&out_dir);

    println!("cargo:rerun-if-changed=src/parser/inlines/uri-schemes.csv");
    println!("cargo:rerun-if-changed=data/math_symbols.json");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Bakes the pinned unicode-math baseline into zero-parse runtime lookup tables.
fn generate_math_symbols(out_dir: &std::path::Path) {
    let json = fs::read_to_string("data/math_symbols.json")
        .expect("read data/math_symbols.json; run `task math-symbols:sync` if missing");
    let file: RawMathSymbols =
        serde_json::from_str(&json).expect("data/math_symbols.json must be valid");
    assert_eq!(file.source.repository, UNICODE_MATH_REPOSITORY);
    assert_eq!(file.source.revision, UNICODE_MATH_REVISION);
    assert_eq!(file.source.path, "unicode-math-table.tex");
    assert_eq!(file.source.license, "LPPL-1.3c-or-later");
    assert_eq!(file.symbols.len(), EXPECTED_MATH_SYMBOLS);

    let render_info = |class: RawMathClass, delimiter: Option<RawDelimiterRole>| {
        let delimiter = delimiter.map_or("None".to_owned(), |role| {
            format!("Some({})", role.variant())
        });
        format!("atom_info({}, {delimiter})", class.variant())
    };

    let mut commands = phf_codegen::Map::new();
    let mut characters = BTreeMap::new();
    for (codepoint, command, class, delimiter) in &file.symbols {
        commands.entry(command.as_str(), render_info(*class, *delimiter));
        let value = u32::from_str_radix(codepoint, 16)
            .unwrap_or_else(|_| panic!("invalid math-symbol code point `{codepoint}`"));
        let character =
            char::from_u32(value).unwrap_or_else(|| panic!("invalid Unicode scalar U+{codepoint}"));
        characters.insert(character, (*class, *delimiter));
    }

    let mut out = String::new();
    writeln!(
        out,
        "// @generated by build.rs from data/math_symbols.json—do not edit."
    )
    .unwrap();
    writeln!(
        out,
        "static UNICODE_MATH_COMMANDS: MathCommandMap = {};",
        commands.build()
    )
    .unwrap();
    writeln!(
        out,
        "static UNICODE_MATH_CHARS: &[(char, MathAtomInfo)] = &["
    )
    .unwrap();
    for (character, (class, delimiter)) in characters {
        writeln!(
            out,
            "    ({character:?}, {}),",
            render_info(class, delimiter)
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();

    fs::write(out_dir.join("math_symbols.rs"), out).expect("write generated math-symbol table");
}

/// Extracts the lowercased scheme names (first column) from the IANA CSV.
///
/// Minimal RFC 4180 reader: we only need each record's first field, but must
/// honor quoted fields because later columns embed commas and newlines.
/// Registry annotations such as `shttp (OBSOLETE)` keep only the leading token.
fn parse_iana_schemes(csv: &str) -> Vec<String> {
    let mut schemes = Vec::new();
    let mut chars = csv.chars().peekable();
    let mut header = true;
    while chars.peek().is_some() {
        let mut field = String::new();
        let mut in_quotes = false;
        while let Some(&c) = chars.peek() {
            if in_quotes {
                chars.next();
                if c == '"' {
                    if chars.peek() == Some(&'"') {
                        chars.next();
                        field.push('"');
                    } else {
                        in_quotes = false;
                    }
                } else {
                    field.push(c);
                }
            } else if c == '"' {
                chars.next();
                in_quotes = true;
            } else if c == ',' || c == '\n' || c == '\r' {
                break;
            } else {
                chars.next();
                field.push(c);
            }
        }
        let mut in_quotes = false;
        while let Some(&c) = chars.peek() {
            chars.next();
            match c {
                '"' if in_quotes && chars.peek() == Some(&'"') => {
                    chars.next();
                }
                '"' => in_quotes = !in_quotes,
                '\n' if !in_quotes => break,
                _ => {}
            }
        }
        if header {
            header = false;
            continue;
        }
        if let Some(name) = field.split_whitespace().next() {
            schemes.push(name.to_ascii_lowercase());
        }
    }
    schemes
}
